[PTkSdict]
web = "http://swaj.net/sdict/"
platforms = [ "Linux", "Windows", "Mac",]
license = "GPL"
last_modified = "2013-05-06"
last_release = "2.0.0rc5"

["Sdictionary for Symbian"]
web = "http://swaj.net/epoc/symbian/index.html"
platforms = [ "Symbian",]
license = "Unknown"

# [["Sdict-3.0"]
# last_modified = "2007-12-24"

# there is a Perl/Tk-based GUI, and command line tool, both in Perl 5
